### ISSUE TITLE
Adjacent search results should be folded together

### ISSUE THREAD

**Issue by thumphries** [thumphries/hgrep#1]
This is most apparent when searching for a value declaration:

![screen shot 2017-10-03 at 9 41 25 pm](https://user-images.githubusercontent.com/355756/31122234-bb29b624-a886-11e7-80be-0648f12f4266.png)

The current naive implementation shows separate locations, one for the signature, one for the declaration itself.

Ideally, we'd 
- fold through the list of search results
- merge all the adjacent SrcSpans
- pretty-print the combined SrcSpan
- print all the declarations together, one after the other

**Comment by chshersh** [comment]
Hello, @thumphries! I would love to implement this feature during Hacktoberfest if you don't mind :) I found `hgrep` very useful. And I really want to make it better.

**Comment by thumphries** [comment]
Hey! That sounds great, please let me know if you have any questions.

**Comment by bobbyrauchenberg** [comment]
Hey @thumphries @ChShersh i started looking at this also - should i drop it? (not sure what the etiquette is in such situations :) )

**Comment by chshersh** [comment]
@bobbyrauchenberg I've already started implementing this feature... But if @thumphries want me to drop it in favor of you I can do this. I had experience when I implemented major feature in some library in Idris programming language and my changes were rejected. I was sad. But after some time I understood my failure. I didn't tell repository author my intention. [This video](https://www.youtube.com/watch?v=6kGLHXsUQD4) by @ndmitchell helped me to understand how OSS works.
Since then I always discuss everything in issues before I start contribute to project :)

**Comment by bobbyrauchenberg** [comment]
@ChShersh no worries i'm happy to drop it! i would have said sth when i started looking, but i was initially just having a look through the source

**Comment by thumphries** [comment]
Thanks for working it out, I will put up a few more easy issues since there's so much to do :)

**Comment by chshersh** [comment]
@thumphries Am I right that type signature should be merged with value declaration? In that case it's not trivial to detect reliably using current API which search results to combine. I found two non-trivial cases:

1.
```haskell
foo, bar :: String
foo = "foo"
bar = "bar"
```

2. 
```haskell
foo :: String

--- fooo
foo = "fool"
```

Am I right that such cases should be considered very rare and don't care about them at the moment?

**Comment by thumphries** [comment]
We should be able handle those cases correctly. When we are in printSearchResults, it should be clear from looking at the SrcSpan that all three of the declarations above are contiguous. 

So if "foo, bar" ends on line 61 and "foo =" starts on line 62, printSearchResults should merge their locations and print them together. Same if "bar =" is on line 63.

Note that I haven't tried to implement this, so it might be harder than I describe! :)

**Comment by chshersh** [comment]
@thumphries Thanks for you clarification! Probably I just didn't understand this issue well enough. So let me try to clarify my intention once more time: am I right that I should merge all results inside one file into one big result? Well, as I understand, type of function should be combined with body of this function. But problems can happen when parts of function body are far from each other.

Consider next example. Running `hgrep` over my artificial example gives next output:

```haskell
src/Importify/Cabal/Target.hs:69:1-31


68  -- | Directory name for corresponding target.
69  targetIdDir :: TargetId -> Text

src/Importify/Cabal/Target.hs:(70,1)-(72,64)

70  targetIdDir LibraryId               = "library"
71  targetIdDir (ExecutableId exeName)  = "executable@" <> exeName
72  targetIdDir (BenchmarkId benchName) = "benchmark@"  <> benchName

src/Importify/Cabal/Target.hs:80:1-63


80  targetIdDir (TestSuiteId testName)  = "test-suite@" <> testName
```

As I see it now after my changes this should look like this:

```haskell
src/Importify/Cabal/Target.hs:[69:1-31][(70,1)-(72,64)][80:1-63]


68  -- | Directory name for corresponding target.
69  targetIdDir :: TargetId -> Text
70  targetIdDir LibraryId               = "library"
71  targetIdDir (ExecutableId exeName)  = "executable@" <> exeName
72  targetIdDir (BenchmarkId benchName) = "benchmark@"  <> benchName
80  targetIdDir (TestSuiteId testName)  = "test-suite@" <> testName
```

Can you confirm that I understood issue correctly?

**Comment by thumphries** [comment]
Only adjacent declarations should be combined. So, for your example, I think it should come out like this:

```haskell
src/Importify/Cabal/Target.hs:(69, 1)-(72,64)


68  -- | Directory name for corresponding target.
69  targetIdDir :: TargetId -> Text
70  targetIdDir LibraryId               = "library"
71  targetIdDir (ExecutableId exeName)  = "executable@" <> exeName
72  targetIdDir (BenchmarkId benchName) = "benchmark@"  <> benchName

src/Importify/Cabal/Target.hs:80:1-63


80  targetIdDir (TestSuiteId testName)  = "test-suite@" <> testName
```

- The first two results were combined because 69 and 70 are right next to one another.
- The second result is not combined, because of the gap between 72 and 80.
- Note that the location formatting didn't change, we just constructed a bigger `SrcSpan` from the two locations

Hope that's a little clearer, sorry for the ambiguity.

**Comment by thumphries** [comment]
You will find everything you need to inspect and combine the `SrcSpan` here: https://downloads.haskell.org/~ghc/8.0.2/docs/html/libraries/ghc-8.0.2/SrcLoc.html#g:4
