### ISSUE TITLE
Trim empty lines from results

### ISSUE THREAD

**Issue by thumphries** [thumphries/hgrep#18]
ExactPrint captures the comments and whitespace preceding the definition, so it often gives us a wall of whitespace. It would be nice to ignore this.

- Count the number of empty lines
- Drop those empty lines before printing
- Update the location SrcSpan before printing

**Comment by justanotherdot** [comment]
I'll try to pick this one up but I have a few questions:

* I'd assume I can just drop the lines starting with comments or general white space but are we counting the lines for display purposes? (e.g. "14 empty lines not shown"). I'd assume not.
* Dropping the lines seems easiest at `hgrep/src/Language/Haskell/HGrep/Print.hs`, but it's not entirely clear how to update the SrcSpan from there, considering I can only see it present in `hgrep/src/Language/Haskell/HGrep/Internal/Data.hs` as part of the `ParseError`.

Thanks! :smile:

**Comment by thumphries** [comment]
I think this one will be a one-liner once the pending line numbers PR is merged! Best wait for that. It identifies empty lines.

**Comment by vrom911** [comment]
@justanotherdot  PR #21 is merged now, so you now could simply throw away empty lines. 
Printing is happening in `HGrep.Print` module  `printSearchResult` function. Separation is also already implemented there, all you need is remove `nill` lines from the output. Consider that it should be done for both `PrintLineNums` and `NoLineNums` cases.

**Comment by justanotherdot** [comment]
Thanks @vrom911 ! I didn't know you could do the comma separated trick in type declarations!
