### ISSUE TITLE
Support GHC 8.2

### ISSUE THREAD

**Issue by thumphries** [thumphries/hgrep#2]
I haven't tested yet, but I'm almost certain things will break a little in 8.2.

The codebase should be structured defensively, because this is going to happen over and over again:

- Opaque GHC-derived datatypes like `ParsedSource` should live in GHC-specific modules, like `HGrep.Internal.Data.GHC_8_0`
- Lenses should be generated in GHC-specific modules, like `HGrep.Internal.Lens.GHC_8_0`
- Queries too
- Use CPP to hide old versions
- Ensure future GHC releases will attempt to use the most recent version, hope for forward-compatibility

**Comment by vaibhavsagar** [comment]
I tried building it with 8.2 and it compiled and seemed to run without issues.

**Comment by thumphries** [comment]
You're right! We can probably put this stuff on ice until the GHC syntax tree actually changes.

(ExactPrint is destined to be brittle, I'm quite surprised it worked!)
