### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by thumphries** [thumphries/hgrep#20]
I don't own a single Windows machine to test this, but at a minimum it looks like pce-light will need to go.

**Comment by vaibhavsagar** [comment]
Good news, [`pcre-light` builds on Windows](https://github.com/Daniel-Diaz/pcre-light/issues/7#issuecomment-297831070), and besides that there were no issues getting `hgrep` to build! It's a bit fiddly to set up but it does work:
![hgreponwindows](https://user-images.githubusercontent.com/1525767/31304467-8e46a06e-ab4b-11e7-99f0-7a72363b87ae.PNG)

**Comment by vaibhavsagar** [comment]
Interestingly, the colour support is better on `cmd`:
![hgreponwindowscmd](https://user-images.githubusercontent.com/1525767/31304542-558382e0-ab4d-11e7-9311-43f844701b29.PNG)

**Comment by thumphries** [comment]
That's awesome. Someone warned me on Twitter to stop using `pcre-light`, but I guess they were wrong! Thanks for digging into it.

I'll close this until someone else complains :)
