### ISSUE TITLE
Catch ExactPrint exceptions

### ISSUE THREAD

**Issue by thumphries** [thumphries/hgrep#23]
Just noticed exactprint crashes out with an exception when CPP macros fail, we should catch that and (at the very least) ignore the file.

**Comment by bobbyrauchenberg** [comment]
Hi, can you give an example of how to reproduce this?

**Comment by thumphries** [comment]
Sure!

Foo.hs:

```haskell
{-# LANGUAGE CPP #-}
module FooBar where

#if MIN_VERSION_amazonka(1,4,0)
import           Network.AWS.Prelude as A
#else
import           Network.AWS.Prelude as A hiding ((&))
#endif
```

```
$> hgrep abc Foo.hs

/tmp/Foo.hs:4:5: error:
     error: function-like macro 'MIN_VERSION_amazonka' is not defined
#if MIN_VERSION_amazonka(1,4,0)
    ^
1 error generated.
`gcc' failed in phase `C pre-processor'. (Exit code: 1)
```

When we encounter a file like this anywhere in the repo, the whole program crashes, which is not great. It'd be great to figure out how this error is being thrown (exception? `exit 1`?), because I have no idea. Handling it would be even better. Thanks for inquiring!

**Comment by bobbyrauchenberg** [comment]
Looking into the code, I can see that in `HGrep.hs` we have 

```parseModule :: FilePath -> IO (Either ParseError ParsedSource)``` 

which calls

```EP.parseModule ...```

`EP.parseModule` does CPP preprocessing see:
[exact-print src](https://github.com/alanz/ghc-exactprint/blob/064306d4661247a91f848be5e1a3201921bcfca8/src/Language/Haskell/GHC/ExactPrint/Parsers.hs#L163)

which eventually calls this function [exact-print src](https://github.com/alanz/ghc-exactprint/blob/064306d4661247a91f848be5e1a3201921bcfca8/src/Language/Haskell/GHC/ExactPrint/Parsers.hs#L215`)

So it looks like `ghcWrapper` in `gch-exactprint` ends up calling `GHC.defaultErrorHandler` which does ```exitWith (ExitFailure 1)```

There does look like there's a parser in the exactprint parsers module which parses without running the CPP preprocessor, but when i tried amending the code, it compiled and ran but didn't seem to do anything. Tho this might just be down to my very basic haskell skills :)

I will try and deal with the exception

**Comment by thumphries** [comment]
Thanks for digging that up!

If the code is calling exitWith, under the hood that's implemented as an ExitException: https://hackage.haskell.org/package/base-4.10.0.0/docs/System-Exit.html#v:exitWith

This means we should be able to catch it with Control.Exception.tryJust.

I'll evaluate the other parsers in ExactPrint, but in the meantime that would be a great way to stop the program crashing :)

**Comment by bobbyrauchenberg** [comment]
I've pushed a fix for this https://github.com/thumphries/hgrep/pull/33, which stops the app from crashing when it encounters a file such as the one shown in your example, however there seems (at least to me) to be no way to stop the error from the exact-print library (or more correctly the libraries that it calls) being printed to the console. 

For example, you can see below that `Foo.hs` errors, but whilst the error is handled and execution continues, the error message is printed:

```bash
➜  hgrep git:(catch-exactprint-exceptions) ✗ /Users/bra14/.local/bin/hgrep fastEq **/*.hs

Foo.hs:4:25: error:
     error: token is not a valid binary operator in a preprocessor subexpression
#if MIN_VERSION_amazonka(1,4,0)
    ~~~~~~~~~~~~~~~~~~~~^
1 error generated.
`gcc' failed in phase `C pre-processor'. (Exit code: 1)

src/Language/Haskell/HGrep/Query.hs:85:1-49


85  fastEq :: [Char] -> FastString.FastString -> Bool

src/Language/Haskell/HGrep/Query.hs:(86,1)-(87,33)

86  fastEq s fs =
87    FastString.mkFastString s == fs
```

**Comment by thumphries** [comment]
Yep, that's ok for now. I'd say something there is printing straight to stderr, which is pretty hard to work around. The next step is probably to investigate the non-CPP printers, and/or see if this is something that can be caught inside exactprint.

Thanks for digging into it, I really appreciate it. I'll review that PR shortly.

**Comment by thumphries** [comment]
Handled really well in #33 !
