### ISSUE TITLE
Allow directories as arguments

### ISSUE THREAD

**Issue by thumphries** [thumphries/hgrep#24]
One of the nice things about tools like `ag` is it just automatically recurses through any directory you pass to it. In the absence of any directory arguments, it will implicitly use the current directory. Usually you want to search the current project or metaproject, so this is very useful shorthand.

We should do this. In addition to being convenient, It enables a couple of enhancements that people almost always will want:
- gitignore awareness
- cabal_macros awareness when the file exists #19 
- pulling the extra-extensions from cabal files maybe

Could use `FileManip` or `conduit-find` (or roll the directory traversal from scratch, which isn't the worst idea)

**Comment by justanotherdot** [comment]
You can also do this rather plainly (although I don't know what perf is like), see [here](https://github.com/justanotherdot/stickybeak/blob/recursive-watch/src/Stickybeak.hs#L83). Having a collection of files that you could simply iterate the commands across might be sufficient, depending on what your needs are and if you are willing to wait for accumulating the list before performing the search. The advantage of `FileManip` or `conduit-find` (I _think_) is that you can probably run the actions as you come across files.

**Comment by thumphries** [comment]
You're right, we don't need to use one of those libraries just to recursively list a directory with a single predicate!

I reach for those libraries when I need to compose complicated predicates or write a whole bunch of directory traversals in one go. It's totally not needed in this case, where we just look for `.hs` and `.lhs`.

**Comment by vrom911** [comment]
I would like to implement this feature. It will make the tool more useful and it's very important to have this.

In the `README` you have the command like this:
```
hgrep PrintOpts src/**/*.hs
```
I tried to execute it, but it doesn't work for me :disappointed:  Should this feature support such templates as well?

And also don't you mind me to use more safe library [`path`](http://hackage.haskell.org/package/path)?

**Comment by justanotherdot** [comment]
The globstar `**` is a shell option; on in `bash` >=v4 (I think?) and `zsh` by default. [Here's a link to an SO post on how to turn it on if you are using `bash` and want to try it](https://stackoverflow.com/a/1691202/2748415). I think part of the aim of this to issue is to decouple the reliance on shell-specific features for globbing. 

Might be best to make the safer `path` lib conversion a different PR (first) and then build on that, I'd say, so long as @thumphries is cool with it.

**Comment by thumphries** [comment]
First of all, thanks again for volunteering your time, both of you. I haven't written any code for this project all week and it's still moving forward, which is amazing!

For the first cut of this feature, check if it the argument is a file or directory before parsing it; if it's a directory, recursively search it for hs and lhs files. Eventually we should also respect any gitignore files we encounter, but that should be a different issue

I'd prefer we avoid the path library, given what we need to do is fairly simple. It's a good library, but the bar for adding a dependency should be a little bit higher. Every dependency is a chance for the build to break in the future. The filepath library is a safe inclusion and should provide what we need. If the FilePath type alias bothers you, a newtype around it is a good idea!

Ryan is right, my example uses globstar. Not all shells support it properly, so this directory crawl feature is important. Hgrep could also expand globs passed to it with Glob, though I'm not yet sure if that's a good idea.

**Comment by thumphries** [comment]
Admirably handled in #43 ! Well done all

**Comment by justanotherdot** [comment]
nice! Good work @vrom911  🙂
