### ISSUE TITLE
`stack build` gives error of missing `libpcre` package

### ISSUE THREAD

**Issue by justanotherdot** [thumphries/hgrep#26]
Was going to try to tackle #9, but when running `stack build` with tip of master fails because it can't find pcre-light:

```
Progress: 15/44
--  While building package pcre-light-0.4.0.4 using:
      /home/rjs/.stack/setup-exe-cache/x86_64-linux/Cabal-simple_mPHDZzAJ_1.24.2.0_ghc-8.0.2 --builddir=.stack-work/dist/x86_64-linux/Cabal-1.24.2.0 configure --with-ghc=/home/rjs/.stack/programs/x86_64-linux/ghc-8.0.2/bin/ghc --with-ghc-pkg=/home/rjs/.stack/programs/x86_64-linux/ghc-8.0.2/bin/ghc-pkg --user --package-db=clear --package-db=global --package-db=/home/rjs/.stack/snapshots/x86_64-linux/lts-9.6/8.0.2/pkgdb --libdir=/home/rjs/.stack/snapshots/x86_64-linux/lts-9.6/8.0.2/lib --bindir=/home/rjs/.stack/snapshots/x86_64-linux/lts-9.6/8.0.2/bin --datadir=/home/rjs/.stack/snapshots/x86_64-linux/lts-9.6/8.0.2/share --libexecdir=/home/rjs/.stack/snapshots/x86_64-linux/lts-9.6/8.0.2/libexec --sysconfdir=/home/rjs/.stack/snapshots/x86_64-linux/lts-9.6/8.0.2/etc --docdir=/home/rjs/.stack/snapshots/x86_64-linux/lts-9.6/8.0.2/doc/pcre-light-0.4.0.4 --htmldir=/home/rjs/.stack/snapshots/x86_64-linux/lts-9.6/8.0.2/doc/pcre-light-0.4.0.4 --haddockdir=/home/rjs/.stack/snapshots/x86_64-linux/lts-9.6/8.0.2/doc/pcre-light-0.4.0.4 --dependency=base=base-4.9.1.0 --dependency=bytestring=bytestring-0.10.8.1
    Process exited with code: ExitFailure 1
    Logs have been written to: /home/rjs/misc/hgrep/.stack-work/logs/pcre-light-0.4.0.4.log

    Configuring pcre-light-0.4.0.4...
    Cabal-simple_mPHDZzAJ_1.24.2.0_ghc-8.0.2: The pkg-config package 'libpcre' is
    required but it could not be found
```

Looks like I have `libpcre3`, but seems to only work when I install `libpcre3-dev` (Ubuntu 16.04 is the machine I'm on right now). Was going to make a PR with an installation section of the README but wanted to start the discussion of what should be in there, OS specific details, etc. or if we event want to continue using PCRE vs POSIX regex based on #20.

**Comment by thumphries** [comment]
Hey! A documentation PR would be most welcome!

As per #9 , the project should always be immediately buildable with `stack build`, `cabal new-build`, and `mafia build`, with GHCs 8.0.1 and newer. The README should reflect that.

OS-specific instructions for C libs should eventually include (at least) Ubuntu, Fedora, and OS X. Any info you can be bothered including right now is going to be a huge improvement.

#20 needs to be dealt with eventually, but I have no idea what library to choose instead, nor do I have a Windows box (or even Travis builds for Windows). So it's a much smaller yak to fix the instructions!

**Comment by justanotherdot** [comment]
Per your last point: Do you need full PCRE support or is POSIX acceptable? I suspect POSIX will probably be safer (and not to mention faster) to allow a Windows port but I don't really have any evidence to back that up.

**Comment by thumphries** [comment]
Really not sure! Personally, I used to be a Perl hacker, so when I use non-PCRE regex I get tripped up. For that reason I prefer PCRE if it's at all possible in Windows. Yet to investigate.

Pretty sure IO, parsing, and query structure will always be the performance bottlenecks for `hgrep`, rather than the name matching, so I'm not too worried on that front, even a pure Haskell implementation would probably be OK.

Full disclosure: I plan on eventually turning this into a structural editing tool, so I'd prefer powerful regex libraries capable of interesting stuff like capture groups and substitution.

**Comment by justanotherdot** [comment]
Ah fair enough! Don't meet a lot of Perl hackers (beside my own brother), but I hear how powerful it is.

`ag` and `ripgrep` are primarily focused (when it comes to performance) on choosing which files to look at because you mostly cannot avoid searching the whole file (even if you end up using something like Boyer-Moore of what have you). In this regard, we only want to look at Haskell source but even that could be problematic if it's _all_ Haskell source (per the `amazonka` suggestion` in #4); not sure atm how to speed that up (besides making it parallel). 

I'll try to write up some simple docs that specify installation with stack and Ubuntu and Mac OS to get the party started, at least. I'd prefer to try building with stack on Fedora before adding that.
