### ISSUE TITLE
Line numbers on output

### ISSUE THREAD

**Issue by thumphries** [thumphries/hgrep#3]
When printing a search result, grab the starting line number from the SrcSpan. Use it to prepend pretty line numbers to each line we spit out.

**Comment by vrom911** [comment]
I'm interested in implementing this feature, can I give it a try?

**Comment by thumphries** [comment]
Please do! The relevant data types are in SrcLoc (part of GHC-the-library) - things like SrcSpan and SrcLoc.

I'd expect the code to go somewhere inside printSearchResults.

Let me know if you have any questions!

**Comment by thumphries** [comment]
Implemented in #21 💥
