### ISSUE TITLE
Indentation issue when printing line numbering

### ISSUE THREAD

**Issue by vrom911** [thumphries/hgrep#40]
For the moment [`prependLineNum`](https://github.com/thumphries/hgrep/blob/65b5d06cd812d9ae08b4feeb0357021d13a9b172/src/Language/Haskell/HGrep/Print.hs#L88) function adds the line number and two spaces after the number at the start of each line before printing. The issue appears when line numbers consist of different amount of digits. For instance, this search result can make users confused:
```haskell
99  someFun :: String
100  someFun = "Oops.."
101  ..
```
My proposal is to always make 4 symbols before actual code and the amount of spaces will depend on how many digits is there in line number (I assuming, that Haskell modules will have less than 1000 lines).

So it always would be like this:
```
9   main :: IO ()
99  somefunc :: String
100 someFun = "Oops.."
```

**Comment by vaibhavsagar** [comment]
I don't say this very often, but: what if we used tabs here? They would provide enough space between the line number and the actual code and behave more gracefully across different numbers of digits.

**Comment by thumphries** [comment]
I've been meaning to switch it over to `printf "%4d"`.

> assuming, that Haskell modules will have less than 1000 lines

I've seen them above 1000, but never above 9999! People with 10,000 lines of Haskell in a single module have bigger problems than hgrep. This is a tool for interactive human use, so we should aim for whatever's visually intuitive.

> I don't say this very often, but: what if we used tabs here?

Good point! Curious how that would look. I tried just now and couldn't get anything nice out:

![screen shot 2017-10-12 at 2 04 02 am](https://user-images.githubusercontent.com/355756/31449060-a98f761c-aef1-11e7-8fc3-a1143ca4f039.png)

**Comment by vaibhavsagar** [comment]
I meant instead of the two spaces we currently use :smiley:, not as a way of right-justifying the line numbers. For example:

```haskell
prependLineNum i l = show i <> "\t" <> l
```

**Comment by thumphries** [comment]
Sorry, I can't read.

The largest valid, compiling, useful Haskell module I know of is [`FlipPlus.hs`](https://github.com/mxswd/flip-plus/blob/master/Control/FlipPlus.hs) which is 50,000 lines. Not sure we need to worry about anything bigger.

I vote for `printf "%5d  "`, (trailing two spaces) because I like the right justification. It's what most text editors do. What do you all think?

**Comment by vaibhavsagar** [comment]
Wow. you're right! I had forgotten that my editor behaves like this. I also tried the tab and it takes up too much horizontal space for my liking. `printf "%5d "` works well.

**Comment by vrom911** [comment]
@thumphries @vaibhavsagar I also played a bit with it and I think this one looks cool. My vote for `printf "%5d "` as well :)

**Comment by bobbyrauchenberg** [comment]
i would vote for `%5d` also

**Comment by thumphries** [comment]
Handled admirably in #41 !
