### ISSUE TITLE
Add nix dependencies to stack.yaml?

### ISSUE THREAD

**Issue by bflyblue** [thumphries/hgrep#47]
Consider adding the nix dependencies directly to the `stack.yaml` file? Nix users can then just use `stack --nix build`. I noticed pkgconfig is also a dependency, so if you don't want to go this route, perhaps list it as a dependency in the README.

```
nix:
  packages:
    - pcre
    - pkgconfig
```

**Comment by vaibhavsagar** [comment]
I just ran into this today and was going to submit a PR, thanks for the suggestion!
