### ISSUE TITLE
Support stack

### ISSUE THREAD

**Issue by thumphries** [thumphries/hgrep#9]
I don't use stack, so figuring out how to support it is enough work to warrant its own issue.

Should build with stack build, first time every time.

**Comment by vaibhavsagar** [comment]
Neil Mitchell has [an interesting approach](https://github.com/ndmitchell/neil#quirks) to `stack.yaml` files. Since the current `stack.yaml` would be identical to that generated by `stack init`, maybe you could remove it entirely and test that `stack init && stack build` works with each new release?

**Comment by justanotherdot** [comment]
What's next to do on this ticket? As of #26, `stack build` works fine for me.

```bash
~/misc/hgrep
η stack exec hgrep -- main main/hgrep.hs
main/hgrep.hs:16:1-13



main :: IO ()
main/hgrep.hs:(17,1)-(31,31)

main = do
  IO.hSetBuffering IO.stdout IO.LineBuffering
  IO.hSetBuffering IO.stderr IO.LineBuffering
  opts <- parseOpts
  colour <- detectColour
  case parseQuery (cmdQuery opts) (cmdRegex opts) of
    Left er -> do
      IO.hPutStrLn IO.stderr er
      exitWith (ExitFailure 2)
    Right q -> do
      found <-
        fmap sum $
          for (cmdFiles opts) $ \fp ->
            hgrep (HGrep.PrintOpts colour) q fp
      exitWith (exitCode found)
```

**Comment by thumphries** [comment]
Looks like we'll be able to just remove the `stack.yaml`, so the only thing left to do is ensure Travis does `stack` builds in #5 .

**Comment by justanotherdot** [comment]
Do you want this in `bin/travis_script` or tucked directly into the `.travis.yml`?

**Comment by thumphries** [comment]
I think we can close this. Head over to #5.
